#!/bin/bash
set -o errexit
export REACT_APP_NOTE_TAKING_APP_FE_URL=$NOTE_TAKING_APP_FE_URL
export REACT_APP_NOTE_TAKING_APP_BE_URL=$NOTE_TAKING_APP_BE_URL
export REACT_APP_MONGODB_URI=$MONGODB_URI
export REACT_APP_MONGODB_DBNAME=$MONGODB_DBNAME
npm install && npm run build